### ISSUE TITLE
should be able to remove hard-coded width percents on table so they expand to fit better?

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/crossword#71]
i think that first table wouldn't need multi-line names and tighten it up, worth trying

**Comment by mmcghee18** [comment]
I avoided this

**Comment by mmcghee18** [comment]
I was trying to avoid this where the width of the columns changes in each decade. Both have their downsides I guess...

https://www.loom.com/share/41ed83d96bc54209b8da38f9e4923445
